define("templates", function (require) {
    "use strict";

    return {
        outputAccordion:       require("tpl!templates/outputAccordion.ejs"),
        outputAlert:           require("tpl!templates/outputAlert.ejs"),
        outputBreadcrumbs:     require("tpl!templates/outputBreadcrumbs.ejs"),
        outputButton:          require("tpl!templates/outputButton.ejs"),
        outputButtonBadge:     require("tpl!templates/outputButtonBadge.ejs"),
        outputCarousel:        require("tpl!templates/outputCarousel.ejs"),
        outputCheckboxButton:  require("tpl!templates/outputCheckboxButton.ejs"),
        outputCollapse:        require("tpl!templates/outputCollapse.ejs"),
        outputDismissAlert1:   require("tpl!templates/outputDismissAlert1.ejs"),
        outputDismissAlert2:   require("tpl!templates/outputDismissAlert2.ejs"),
        outputDropdownButton:  require("tpl!templates/outputDropdownButton.ejs"),
        outputInputGroup:      require("tpl!templates/outputInputGroup.ejs"),
        outputJumbotron:       require("tpl!templates/outputJumbotron.ejs"),
        outputLabel:           require("tpl!templates/outputLabel.ejs"),
        outputLink:            require("tpl!templates/outputLink.ejs"),
        outputLinkBadge:       require("tpl!templates/outputLinkBadge.ejs"),
        outputListGroup:       require("tpl!templates/outputListGroup.ejs"),
        outputLoadingButton:   require("tpl!templates/outputLoadingButton.ejs"),
        outputMedia:           require("tpl!templates/outputMedia.ejs"),
        outputModal:           require("tpl!templates/outputModal.ejs"),
        outputNavbar:          require("tpl!templates/outputNavbar.ejs"),
        outputNavbarInverted:  require("tpl!templates/outputNavbarInverted.ejs"),
        outputPageHeader:      require("tpl!templates/outputPageHeader.ejs"),
        outputPager:           require("tpl!templates/outputPager.ejs"),
        outputPagination:      require("tpl!templates/outputPagination.ejs"),
        outputPanel:           require("tpl!templates/outputPanel.ejs"),
        outputPills:           require("tpl!templates/outputPills.ejs"),
        outputPopover:         require("tpl!templates/outputPopover.ejs"),
        outputProgressbar:     require("tpl!templates/outputProgressbar.ejs"),
        outputRadioButton:     require("tpl!templates/outputRadioButton.ejs"),
        outputScrollSpy:       require("tpl!templates/outputScrollSpy.ejs"),
        outputTabs:            require("tpl!templates/outputTabs.ejs"),
        outputThumbnail:       require("tpl!templates/outputThumbnail.ejs"),
        outputThumbnailCustom: require("tpl!templates/outputThumbnailCustom.ejs"),
        outputTooltip:         require("tpl!templates/outputTooltip.ejs"),
        outputWell:            require("tpl!templates/outputWell.ejs")
    };
});